language: ruby

cache: bundler

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0

before_install:
  - gem install bundler

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile

script: "bundle exec rake test"
