name: CI
on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
        rails-version:
          - "4.2"
          - "5.1"
          - "5.2"
          - "6.0"
          - "6.1"
        task:
          - test
    name: ${{ matrix.task }} Rails ${{ matrix.rails-version }} Ruby ${{ matrix.ruby-version }}
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test
