name: CI
on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
          - "3.3"
        rails-version:
          - "6"
          - "7"
          - "8"
        include:
          - {ruby-version: "2.5", rails-version: "4"}
          - {ruby-version: "2.6", rails-version: "4"}
          - {ruby-version: "2.7", rails-version: "5"}
          - {ruby-version: "3.0", rails-version: "6"}
          - {ruby-version: "3.1", rails-version: "7"}

    name: Ruby ${{ matrix.ruby-version }}, Rails ${{ matrix.rails-version }}
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test
